### PR TITLE
Drop Travis and Appveyor

### PR DESCRIPTION
**Pull request by sethaxen**

### CODE REVIEW

**Comment by sethaxen** [comment]
Hmm, Appveyor is running anyways. @kellertuer do we need to remove the Appveyor app to make it stop building? Or will it stop once this is merged into master?

**Comment by kellertuer** [comment]
Interesting, yes we could also remove the app so it does not get triggered by a push

**Comment by sethaxen** [comment]
Okay, well if you approve of dropping these, I'll deactivate the app and then merge this PR.

**Comment by kellertuer** [comment]
Yes, the GitHub Actions seem to run well, so we can drop AppVeyor.

**Pull request merged**
