### PR TITLE
Move ManifoldDiff extension here

### PR DESCRIPTION
**Pull request by mateuszbaran**
See here: https://github.com/JuliaManifolds/ManifoldDiff.jl/issues/20

### CODE REVIEW

**Review by kellertuer — APPROVED** [review]

**Comment by mateuszbaran** [comment]
These new lines most likely won't be cover until [ManifoldDiff](https://github.com/JuliaManifolds/ManifoldDiff.jl/issues/20) is merged, and tests in that PR likely won't pass until this is merged. Which one do you prefer to merge and tag first?

**Comment by kellertuer** [comment]
For me its ore reasonable to remove it from ManifoldDiff first and then add it here, since otherwise there is a version where the extension exists twice.

**Comment by mateuszbaran** [comment]
I have no idea why Manopt gradient tests fail here. Locally they pass fine.

**Comment by kellertuer** [comment]
The error message seems to be quite Diff-related though

**Comment by mateuszbaran** [comment]
Yes, it doesn't see the `adjoint_Jacobi_field` method for `Circle`. That method was in the extension of ManifoldDiff. We have it in this PR now and it's covered by a test so this makes no sense to me.

**Comment by kellertuer** [comment]
Ah, maybe Manopt still checks our some old version? Because currently Manopt/ManifoldDiff/Manifolds in their most recent version do not play well together, since the extension is nowhere (reverted to 0.3.2 to get it working again). So I am not sure how to resolve this. Register this version and hope for the best?

**Comment by kellertuer** [comment]
The same happens for now on Manopt CI, I think the choice of having a version combination without this extension was not that good and a next release here should fix that.

On the other hand it means that there is now combinations of Manifolds and ManifoldDiff that do not work well together (one or two combinations where the extension is nowhere to be found), but I think this can not be avoided.

**Comment by kellertuer** [comment]
I think I found a solution. I will restrict ManifoldDiff in Manopt to 0.3.2, then it should work fine; we register the stochastic PR (maybe also together with the new tutorial update?) as a new version (with the 0.3.2 bound). Then this PR defines a few functions double for Manopt, but that should be fine; afterwards bumping version to 0.3.3 and Manifolds <= this PR should also make Manopt work again.

**Comment by mateuszbaran** [comment]
OK, that sounds like a good plan.

**Comment by kellertuer** [comment]
It worked :) After this is merged and registered I can use the version number from here and Diff 0.3.3 as lower bounds in Manopt, for the next version.

**Comment by mateuszbaran** [comment]
Great! So I think this PR can be merged now?

**Comment by kellertuer** [comment]
Yes :)

**Pull request merged**
