### PR TITLE
Moving group-related tests to ManifoldTests

### PR DESCRIPTION
**Pull request by mateuszbaran**
This will be useful in https://github.com/JuliaManifolds/FunManifolds.jl/pull/10 .

### CODE REVIEW

**Comment by kellertuer** [comment]
Seems reasonable, maybe formatter run is missing?

**Comment by mateuszbaran** [comment]
Yes it is, there is also a weird failure on nightly.

**Comment by mateuszbaran** [comment]
It looks like there was another change to printing recently: https://github.com/JuliaLang/julia/pull/37085 .

**Comment by kellertuer** [comment]
Good to know – if we encapsulate those tests further, as I started for one of them, this would automatically be correct (though I don't completely remember where I did that ;)).

**Pull request merged**
