### PR TITLE
More general columnwise multiplication action

### PR DESCRIPTION
**Pull request by olivierverdier**
This makes `ColumnwiseMultiplicationAction` more general, as it works now with any subtype of `AbstractMatrixGroup`, a new abstract type above `GeneralLinear` and `GeneralUnitary`.

Feel free to change the new name if you don't like it!

Maybe other groups could be subgroups of this new abstract type?

I also think more actions could be defined with respect to that abstract type instead of `GeneralUnitary`.

What do you think?

### CODE REVIEW

**Comment by olivierverdier** [comment]
Yes, that's a good point, I agree with that.

Maybe something else is required for that: a *diagonal action*, that is, when you have an action of $`G`$ on a space $`V`$, you should be able to construct the *diagonal action* of $`G`$ on $`V^n`$ for some integer $`n`$.

Then the columnwise action on $`d\times n`$ matrices is essentially a diagonal action.

That would solve the issue in the most general way, I believe?

So a rough sketch of how it would look like is:
```julia
struct ColumnwiseMultiplicationAction{
    TA<:AbstractGroupAction{TAD}
} <: AbstractGroupAction{TAD}
    action::TA
end

function apply(A::ColumnwiseMultiplicationAction, a, p)
    return apply(DiagonalAction(A.action, size(p,2)), a, p) # but DiagonalAction doesn't exist yet (and not sure if `p` or `eachcol(p)`)
end
```

**Comment by kellertuer** [comment]
Just a first super small remark. In `LieGroups.jl` there is only one (concrete) type `LieGroup{Field, Manifold, GroupOperation}` would a MatrixLieGroup there make sense as well? Then we need `AbstractLieGroup` somewhen there (maybe anyways) – or is it more useful to do an `AbstractMatrixMultiplicationGroupOperation` since we have a `MultiplicationGroupOperation` already anyways?

**Comment by mateuszbaran** [comment]
> Maybe something else is required for that: a _diagonal action_, that is, when you have an action of 

Good idea, I will think about it.

> Just a first super small remark. In `LieGroups.jl` there is only one (concrete) type `LieGroup{Field, Manifold, GroupOperation}` would a MatrixLieGroup there make sense as well? Then we need `AbstractLieGroup` somewhen there (maybe anyways) – or is it more useful to do an `AbstractMatrixMultiplicationGroupOperation` since we have a `MultiplicationGroupOperation` already anyways?

At the moment it's not entirely clear what that abstract type would exactly mean. I think we can implement the key idea here without that type anyway, so maybe there is no need to think about implementing it in LieGroups.jl.

**Comment by olivierverdier** [comment]
Yes, I suppose it could make sense for `LieGroups.jl` as well?

But I'm not 100% percent sure that this is the correct way to handle the issue in this case, since, as @mateuszbaran observed, multicolumn action should also be available for direct and semidirect product, and the current solution doesn't address these cases. I honestly don't know what the best solution would be.

**Comment by kellertuer** [comment]
Sure, taking this as a bit of a playground and experiment sounds good. I feel it might be nicer to introduce an `AbstractMultiplicationOp` and a `MatrixOp` or so on the operations side and subtype there. But I have not yet fully thought through that and all ist implications either.

**Comment by mateuszbaran** [comment]
I've switched `AbstractMatrixGroup` to a union type `MatrixGroup` for now. This should now be a simple extension that won't need too much consideration and we can think about something more general for LieGroups.jl later. Is that OK?

**Comment by olivierverdier** [comment]
Yes, I think that will do, thank you.

**Review by mateuszbaran — APPROVED** [review]

**Pull request merged**
