### PR TITLE
Documentation clarification

### LINKED ISSUE #743: Discrepancy in documentation: at what point is vector X in `translate_diff`
https://juliamanifolds.github.io/Manifolds.jl/stable/manifolds/group.html#Manifolds.translate_diff-Tuple{AbstractDecoratorManifold,%20Vararg{Any}}

`translate_diff(G::AbstractDecoratorManifold, p, q, X, conv::ActionDirectionAndSide=LeftForwardAction())`

- fist sentence and math: "tangent vector X ∈ T**q**G"

- but in note: "X is stored at the point **p** ∈ G"

### PR DESCRIPTION
**Pull request by olivierverdier**
Fixes #743

### CODE REVIEW

**Comment by kellertuer** [comment]
Thanks for the quick fix. Do you want to add a small entry for the changelog as well? Though a “typos fixed” one might be there after merging #741 anyways.

**Comment by olivierverdier** [comment]
It's easier for me if you merge as is, if possible? But feel free to add an entry to the changelog if you think it's necessary.

**Comment by kellertuer** [comment]
Hm, now that you seem to have the news entry (sorry I accidentally had that on master, made a mistake there) we have a merge conflict here, but if you reset / resolve that, sure I can merge.

**Comment by kellertuer** [comment]
Ah I can edit myself. Then I can merge this now as well. Thanks for fixing!

**Pull request merged**
