### PR TITLE
Introduce EmbeddedBackend

### PR DESCRIPTION
**Pull request by kellertuer**
Solves #454. 

The `EmbeddedBackend´ contains the gradient (derivative, jacobian) of a function $f$ defined on a manifold that describe its gradient (derivative, jacobian) as a function extended into the embedding. Similar t Euclidean tools available they hence return Euclidean gradients (derivatives, Jacobins) that have to be converted.

* We should find a way to maybe also introduce mutating variants 
* Is the design ok this way?
* Yes, documentation is missing.

### CODE REVIEW

**Comment by mateuszbaran** [comment]
Yes, I think the design is essentially correct. A few points to consider:
1. Maybe `ExplicitEmbeddedBackend` would be a better name that would highlight that the main feature of this backend.
2. `struct EmbeddedBackend` could just store a `NamedTuple` with functions so that we don't have to add a new field each time a new function is added, and it could then be even extended without modifying Manifolds.jl.
For example
```julia
struct ExplicitEmbeddedBackend{TF<:NamedTuple} <: AbstractDiffBackend
    funs::TF
end
ExplicitEmbeddedBackend(; kwargs...) = ExplicitEmbeddedBackend{typeof(values(kwargs))}(values(kwargs))
```
3. `ExplicitEmbeddedBackend` could also store the function these gradients, differentials and Jacobians correspond to so that it could for example be checked in specific methods that the function given to, for example, `_derivative` is the same one someone wrote the gradient for.

**Comment by mateuszbaran** [comment]
> That would be the `function` field for example, yes; the only thing that might be misleading then is, that the `_gradient`,... have f as their first argument which – if we store it – is a little double information in the arguments?

That's why I think that storing function in `ExplicitEmbeddedBackend` should be optional, only if someone wants the safety.

**Comment by kellertuer** [comment]
> 3. `ExplicitEmbeddedBackend` could also store the function these gradients, differentials and Jacobians correspond to so that it could for example be checked in specific methods that the function given to, for example, `_derivative` is the same one someone wrote the gradient for.

I have one further question to this one – how would I check (in “specific methods”) that the functions are the same and how would I do that? For now I would just check whether the named tuple has the field required for `gradient` or `gradient!` and throw an error otherwise, but how do I check whether functions are the same and why would I do that? Gradients and Derivatives are different...

**Comment by kellertuer** [comment]
I have not yet done the testing, but the modelling and documentation should be complete.

**Comment by mateuszbaran** [comment]
> I have one further question to this one – how would I check (in “specific methods”) that the functions are the same and how would I do that? For now I would just check whether the named tuple has the field required for `gradient` or `gradient!` and throw an error otherwise, but how do I check whether functions are the same and why would I do that? Gradients and Derivatives are different...

I imagined something like
```julia
function check_expected_function(f, e::ExplicitEmbeddedBackend)
    if haskey(e.functions, :func) && if f !== e.functions.func
        error("Wrong function: expected $(e.functions.func), received $f")
    end
end

function _gradient(f, p, e::ExplicitEmbeddedBackend)
    check_expected_function(f, e)
    g = get(e.functions, :gradient, Missing())
```

**Comment by kellertuer** [comment]
Yes one could do that but in most cases we (up to now) where quite lazy in checking (by default, so only if you activate checking we checked things).

**Comment by mateuszbaran** [comment]
Here you have to activate the check as well :slightly_smiling_face:, otherwise it is just not performed.

**Comment by kellertuer** [comment]
Well you implicitly activate it by providing a cost function in the backend, that would be a little implicit, I think. I will think about how to best realise this.

**Comment by mateuszbaran** [comment]
OK, so let's leave it out of this PR if you don't like it.

**Comment by mateuszbaran** [comment]
I thought it would be a nice quick addition but now I see that it may indeed be confusing unless carefully designed, so let's just forget about it.

**Comment by kellertuer** [comment]
But, hm, this is what Pymanopt and Manopt do with there `egrad`s, so I hope we find a way to cover that as well.

**Comment by mateuszbaran** [comment]
What do you mean by "this"? This PR should work fine for gradients.

**Comment by kellertuer** [comment]
Ah then I misread the last parts of the discussion here. I will check but I think this should nearly be good to go (+- tests).

**Comment by mateuszbaran** [comment]
Yes, I only became skeptical about `check_expected_function`, everything else looks fine :slightly_smiling_face: .

**Comment by kellertuer** [comment]
ok löste just leave that out, I do not feel good about that, either.

**Comment by kellertuer** [comment]
I added tests for the current state based on Rayleigh quotient and I hope this does the code coverage – then this is good to go.

**Review by mateuszbaran — APPROVED** [review]
Nice, I think it can be merged when coverage passes.

**Pull request merged**
