### PR TITLE
Simplify project! for Stiefel

### PR DESCRIPTION
**Pull request by dahong67**
Do simplifications of `project!` method discussed in #141 and mentioned in #142.

Key idea is that `s.U' * s.U` in the previous implementation should (up to numerical issues) be approximately `I` in which case the remaining code simplifies.

### CODE REVIEW

**Comment by sethaxen** [comment]
Better yet, now master should just work, so merge master in, and if it passes, I'll merge the PR.

**Comment by sethaxen** [comment]
Oh nevermind, I see that the CI is running correctly after reopening, it's just that the checks also show the old failed CI because those have different names. Okay, we'll just see if it passes.

**Comment by dahong67** [comment]
Wow, you are quite efficient. Thanks for resolving the testing stuff and merging! :)

**Comment by kellertuer** [comment]
Thanks for helping and contributing :)

**Pull request merged**
