### PR TITLE
Propose the fix for #522.

### PR DESCRIPTION
**Pull request by kellertuer**

### CODE REVIEW

**Comment by kellertuer** [comment]
Maybe an alternative to have both variants as a possibility would be to keep the function as is and do the Lie algebra projection for the group manifold analoga.

**Comment by kellertuer** [comment]
I feel this variant should actually be the best choice: To have both.

For _Manigolds (`Rotations`, `OrthogonalMatrices`, `UnitaryMatrices`) we keep the representation as is (that is `X` is the tangent vector and not necessarily skew, but a rotated skew symmetric), for Lie groups (`Orthogonal`, `SpecialOrthogonal`, `SpecialUnitary`, `Unitary`) we use the Lie group representation. This way it is easy to have either of the representations, depending on what the user wants – in a precisely distinct way.

**Comment by kellertuer** [comment]
Uff. This might be more work than I thought because we have so many special variants of exp/log that now have to be doubled and adapted for the other representation case.

**Comment by kellertuer** [comment]
hm, seems really more complicated than I thought. So I will wait for the decision whether we want to unify it and in which way.

**Comment by kellertuer** [comment]
So if I understand correctly it is not only complicated to finish this but even more to get it work together with differentiation again? I would maybe propose to close this?

**Comment by mateuszbaran** [comment]
This would be a lot of work to finish for not much benefit so I'd suggest closing it.

**Pull request closed without merging**
