### PR TITLE
CompatHelper: bump compat for "SpecialFunctions" to "1.0"

### PR DESCRIPTION
**Pull request by sethaxen**
This pull request changes the compat entry for the `SpecialFunctions` package from `0.8, 0.9, 0.10` to `0.8, 0.9, 0.10, 1.0`.

This keeps the compat entries for earlier versions.

Note: I have not tested your package with this new compat entry. It is your responsibility to make sure that your package tests pass before you merge this pull request.

### CODE REVIEW

**Comment by kellertuer** [comment]
Does it maybe help keeping one of them open to not delete one every day?

**Comment by mateuszbaran** [comment]
I've left one open: https://github.com/JuliaManifolds/Manifolds.jl/pull/258 and it looks like it doesn't help.

**Comment by sethaxen** [comment]
I've never seen this before, so I'm wondering if something just went wrong this time.

**Comment by kellertuer** [comment]
Oh, I wasn't aware of the other one, sorry.

**Pull request closed without merging**
