### PR TITLE
Fix solve_exp_ode not updating position

### LINKED ISSUE #740: solve_exp_ode has wrong function signature in docs
In https://github.com/JuliaManifolds/Manifolds.jl/blob/e31e7b088b402af19741ef3b300eccc850d96edc/src/manifolds/ConnectionManifold.jl#L374, the doc definition disagrees with the definition in e.g. https://github.com/JuliaManifolds/Manifolds.jl/blob/e31e7b088b402af19741ef3b300eccc850d96edc/ext/ManifoldsOrdinaryDiffEqExt.jl#L31: It should be
```julia
solve_exp_ode(
        M::ConnectionManifold,
        p,
        X,
        t::Number;
        B::AbstractBasis,
        backend::AbstractDiffBackend = default_differential_backend(),
        solver = AutoVern9(Rodas5()),
        kwargs...,
    )
``` 
instead of
```julia
solve_exp_ode(
        M::ConnectionManifold,
        p,
        X,
        t::Number,
        B::AbstractBasis;
        backend::AbstractDiffBackend = default_differential_backend(),
        solver = AutoVern9(Rodas5()),
        kwargs...,
    )
```

### LINKED ISSUE #744: `solve_exp_ode` does not ever update position
`solve_exp_ode` seems to always return the starting point `p` for any input. See e.g.
```julia 
using Manifolds
using OrdinaryDiffEq
E = Euclidean(3)
p = [0, 0, 0] # point in E
A = get_default_atlas(E)
i = Manifolds.get_chart_index(E, A, p)
B = Manifolds.induced_basis(E, A, i, TangentSpaceType())
X = [0, 0, 1] # tangent vector
time = 1

Manifolds.solve_exp_ode(E, p, X, time; basis=B)
```
which returns `[0, 0, 0]` (i.e. just the starting point `p`).

### PR DESCRIPTION
**Pull request by r0uv3n**
Fixes #744 and fixes #740. Also add some new tests that fail without the fix for #744.

### CODE REVIEW

**Comment by kellertuer** [comment]
Nice!

The one small hint failing is an entry in the changeling (NEWS.md), if you could add that as well, this looks perfect!

**Comment by r0uv3n** [comment]
Should I just add a new minor version number for this?

**Comment by kellertuer** [comment]
yes, as date you could put “unreleased” we will add the date when we register the new version; for the rest just follow the scheme that is already there :)

**Review by kellertuer — APPROVED** [review]
Looks good to me. Thanks for your contribution!

**Review by mateuszbaran — APPROVED** [review]
Thanks, this looks right to me.

**Pull request merged**
