### PR TITLE
Add CompatHelper as GitHub Action

### PR DESCRIPTION
**Pull request by sethaxen**

### CODE REVIEW

**Comment by kellertuer** [comment]
We could do the same with `ManifoldsBase`.

**Comment by sethaxen** [comment]
> We could do the same with `ManifoldsBase`.

Does it need it? ATM its only compat entry has no upper bound to update.

**Comment by kellertuer** [comment]
As far as I read, it would be good, if it gets an upper bound; but for compat helper you'Re right: we don't need compat helper (yet) for just one entry

**Comment by mateuszbaran** [comment]
Technically, the only dependency of `ManifoldsBase` is Julia (and two of its stdlibs). I think we can manually update it when Julia 2.0 is released 🙂 .

**Pull request merged**
