### PR TITLE
Split tests into groups for CI

### PR DESCRIPTION
**Pull request by sethaxen**
As proposed in #144, this PR splits tests into groups for faster runtimes. It's currently 3 groups with roughly equal runtimes. To reduce the number of jobs, I discontinued testing against 1.3, but we can always turn that back on.

I also saw that there was a huge runtime difference (5-6 minutes) between the statistics tests for Julia 1.0 and 1.4, coming entirely from `median` on the sphere running for the maximum number of iterations. Reducing the tolerances fixed that.

### CODE REVIEW

**Comment by mateuszbaran** [comment]
Thanks, that's a good idea. I also think we can discontinue testing on 1.3. Maybe we could have another job for testing static arrays on Julia 1.4? We already have TEST_STATIC_SIZED.

**Comment by sethaxen** [comment]
> Despite Mac OS being slow as so often in tests, this is really neat!

Yeah, we'll see how fast it is in the end. 38 different jobs is quite a lot. As long as the total suite runs significantly faster than the 35-40 minutes that we saw with GitHub Actions before splitting, then I think it's worth it. 

I added a new workflow for running CI on statically sized matrices. But this also repeats a lot of computation; ideally we would test statically sized or not statically sized, but not both. It's currently failing. Could someone take a look at that error message?

**Comment by mateuszbaran** [comment]
I've checked these error messages and my commit should fix that problem.

**Comment by sethaxen** [comment]
It seems like the changes in this PR really help with Travis but for GitHub Actions don't make much of a difference. Runtime is still 30-40 minutes for GA. But since for GA, fast fail mode is the default (if one job fails, it kills all jobs), splitting into groups means we fail faster, which is nice for not filling up the queue. So with that, I think this PR is ready to merge.

**Comment by kellertuer** [comment]
The test suite looks really nice, but why did code coverage reduce by 16%?

**Comment by sethaxen** [comment]
I don't know. It could be the usual codecov nonsense. If you look through the logs, the jobs that ran the tests it says it doesn't see were all run, and code coverage was uploaded. The commit it's comparing to was one that didn't run Travis, so maybe that messed with it somehow. We could merge and see after the suite runs on master whether that fixes the codecov issues. If not, we could revert and troubleshoot.

**Comment by kellertuer** [comment]
Hm, ok, let's hope its just codecov nonsense then. I just noticed, because I invested quite some time writing tests for edge cases.

**Pull request merged**
