### PR TITLE
introduce broadcasting for all _HyperbolicTypes

### PR DESCRIPTION
**Pull request by kellertuer**
by passing on the neccessary functions to the value field. This addresses #10 for the hyperbolic types.

### CODE REVIEW

**Comment by kellertuer** [comment]
Locally formatter ran just fine. I have to check somewhen, what causes it to even fail (not only report a wrongly formatted code) here.

**Comment by kellertuer** [comment]
@mateuszbaran may I remove tests for Julia 1.6 (or at least ambiguity-tests) until we have reduced/removed the 119 ambiguities?

**Comment by kellertuer** [comment]
...and I ran into a slight problem when writing the tests – currently if we have one of the hyperbolic types, writing `2 .* X` yields and array (with the correctly broadcasted values), but not the type again.

**Comment by mateuszbaran** [comment]
> @mateuszbaran may I remove tests for Julia 1.6 (or at least ambiguity-tests) until we have reduced/removed the 119 ambiguities?

Sure, I suggest not testing for ambiguities on 1.6 at all for now.

> ...and I ran into a slight problem when writing the tests – currently if we have one of the hyperbolic types, writing `2 .* X` yields and array (with the correctly broadcasted values), but not the type again.

I think that can't be fixed without defining custom broadcasting style. Do you want me to fix it?

**Comment by kellertuer** [comment]
Well I tried to see how a broadcast style would have to be done – and I defined it and a `similar` function (cf https://docs.julialang.org/en/v1/manual/interfaces/#man-interfaces-broadcasting) just that I did not use an `ArrayStyle` since the hyperbolic types are not abstract arrays – but all I did did not have any effect whatsoever on the broadcast. So sure feel free to illustrate how that is supposed to work

This

````
        Base.BroadcastStyle(::Type{<:$T}) = Broadcast.Style{$T}()
        function Base.similar(bc::Broadcast.Broadcasted{Broadcast.Style{$T}}, ::Type{S}) where {S}
            return $T(simlar(Array{S}, axis(bc)))
        end
````

is how it does _not_ work ;)

**Comment by mateuszbaran** [comment]
OK, a few problems here:
1) `broadcastable` didn't recognize hyperbolic types so it tried collecting it (and that's why you needed `iterate` in the first place). This removed the hyperbolic wrapper so you didn't see it after broadcasting.
2) You didn't have broadcasting mixing rules (so Julia didn't know how to broadcast a hyperbolic vector with a scalar).
3) This style of broadcasting has real trouble preserving the container type (`Array`, `SArray` etc.) so I changed it to something similar to `ProductRepr`.
4) Do you actually want broadcasting for hyperbolic point types?

**Comment by kellertuer** [comment]
1. I don't understand, what's trying tried collecting it here ?
2. Ah, yes, those I missed
3. uff. And you had to introduce so much magic to fix that? While I now understand the point in 2) – lines 149-182 are just indecipherable magic for me. 
4. Sure I want that, if all points/vectors have broadcast that would make the Manopt code nicer (again).

**Comment by mateuszbaran** [comment]
1. You can take a look here: https://github.com/JuliaLang/julia/blob/master/base/broadcast.jl#L685-L690 . `broadcastable` is called on basically every thing you broadcast. Some things are wrapped in `Ref` so they broadcast as scalars, some are untouched (like arrays) and everything else by default is `collect`ed. That is what was happening in your code.
2. :slightly_smiling_face: 
3. I think there is another way to do this but it may turn out even more convoluted than that code. I think someone needs to finally make a cheat sheet for Julia's indexing and broadcasting...
4. OK, I'll leave it then.

**Comment by kellertuer** [comment]
Thanks for the explanation. Do you have a case in mind to cover the last 3 lines, that are new but not yet covered?

**Comment by mateuszbaran** [comment]
Sure, that case should be simple broadcast-assignment like `X2 .= X1` where both are hyperbolic TVectors. I'll add it later, I'm working on something different now.

**Comment by kellertuer** [comment]
Thanks for the explanation and for directly providing it, before I could reach a computer, I had the same idea to easily add that test :)

**Review by mateuszbaran — APPROVED** [review]

**Pull request merged**
