### PR TITLE
Some fixes for vector handling on `CircleGroup`

### PR DESCRIPTION
**Pull request by mateuszbaran**
Fixes the issue reported in https://github.com/JuliaManifolds/Manifolds.jl/issues/415 .

I think `number_of_coordinates` should ideally have transparency (it's overloaded for `Circle`), what do you think @kellertuer ? Also, I'm not sure if the other `parent` transparencies for `AbstractGroupManifold` are actually correct.

### CODE REVIEW

**Comment by kellertuer** [comment]
Yes it should have transparency – is that already the fix? That's cool.

For the other, please check, maybe some should be `:transparent`.

**Comment by mateuszbaran** [comment]
Transparency for `number_of_coordinates` needs to be introduced in ManifoldsBase.jl, I've just added manually transparency for `CircleGroup` (that's the only place where it currently matters I think).

**Comment by mateuszbaran** [comment]
Hm, this breaks `SpecialEuclidean` in a really annoying way: product manifold methods can no longer use matrix variants of `submanifold_components`.

**Comment by mateuszbaran** [comment]
I've applied what looks like the simplest fix but I don't really like it.

**Comment by kellertuer** [comment]
Why don't you like it? It seems to use a similar approach to `SpecialEuclidean`?

**Comment by mateuszbaran** [comment]
It feels a bit weird that `submanifold_componenets` needs to be defined for both manifold and the `SpecialEuclidean` group but maybe that's OK.

**Comment by kellertuer** [comment]
I think that is ok.

**Comment by mateuszbaran** [comment]
@kellertuer is it OK to merge this? The coverage failure seems to be unrelated and I think the solution is finally right.

**Review by kellertuer — APPROVED** [review]
I was waiting for exactly some comment on the coverage. Then it's ok.

**Pull request merged**
