### PR TITLE
Make more functions accept `Identity`

### PR DESCRIPTION
**Pull request by mateuszbaran**
Addresses point 4 of #497 .

### CODE REVIEW

**Comment by dehann** [comment]
Hi, I looked through the files changed on this PR but did not see `SpecialOrthogonal(N)`.  Just wanted to ask if that could be added too please?

This is what I ran into just now:
```julia
M = SpecialOrthogonal(3)

# works fine
r = hat(M, Identity(M), randn(3)) 
R1 = exp(M, identity_element(M), r)

# error stack below
R2 = exp(M, Identity(M), r)  



ERROR: MethodError: no method matching similar(::Identity{MultiplicationOperation}, ::Type{Float64})
Closest candidates are:
  similar(::Union{LinearAlgebra.Adjoint{T, var"#s861"}, LinearAlgebra.Transpose{T, var"#s861"}} where {T, var"#s861"<:(AbstractVector)}, ::Type{T}) where T at /usr/local/share/julia-1.7.3/share/julia/stdlib/v1.7/LinearAlgebra/src/adjtrans.jl:206
  similar(::Union{LinearAlgebra.Adjoint{T, S}, LinearAlgebra.Transpose{T, S}} where {T, S}, ::Type{T}) where T at /usr/local/share/julia-1.7.3/share/julia/stdlib/v1.7/LinearAlgebra/src/adjtrans.jl:210
  similar(::Union{LinearAlgebra.Adjoint{T, S}, LinearAlgebra.Transpose{T, S}} where {T, S}, ::Type{T}, ::Tuple{Vararg{Int64, N}}) where {T, N} at /usr/local/share/julia-1.7.3/share/julia/stdlib/v1.7/LinearAlgebra/src/adjtrans.jl:211
  ...
Stacktrace:
 [1] allocate(a::Identity{MultiplicationOperation}, T::Type)
   @ ManifoldsBase ~/.julia/packages/ManifoldsBase/DQUn5/src/ManifoldsBase.jl:61
 [2] allocate(#unused#::Rotations{3}, a::Identity{MultiplicationOperation}, T::Type)
   @ ManifoldsBase ~/.julia/packages/ManifoldsBase/DQUn5/src/ManifoldsBase.jl:74
 [3] allocate_result
   @ ~/.julia/packages/ManifoldsBase/DQUn5/src/ManifoldsBase.jl:103 [inlined]
 [4] exp(M::Rotations{3}, p::Identity{MultiplicationOperation}, X::Matrix{Float64})
   @ ManifoldsBase ~/.julia/packages/ManifoldsBase/DQUn5/src/exp_log_geo.jl:16
 [5] exp
   @ ~/.julia/packages/ManifoldsBase/DQUn5/src/nested_trait.jl:291 [inlined]
 [6] exp
   @ ~/.julia/packages/ManifoldsBase/DQUn5/src/nested_trait.jl:282 [inlined]
 [7] exp(M::SpecialOrthogonal{3}, p::Identity{MultiplicationOperation}, X::Matrix{Float64})
   @ ManifoldsBase ~/.julia/packages/ManifoldsBase/DQUn5/src/nested_trait.jl:275
 [8] top-level scope
   @ REPL[10]:1
```

**Comment by kellertuer** [comment]
@dehann  What you actually do there is `exp_lie` :) 

@mateuszbaran  I am not yet 100% sure I am so happy with having so much code to introduce `Identity` everywhere, can we maybe do that with the group trait? something like
`exp(::TraitList{IsGroupManifold}, M::DecoratorManifold, ::Identity, X) = exp_lie(M,X)`?
the one ting I do not directly see here is that it in principle also has to be “the right” identity here.

**Comment by mateuszbaran** [comment]
> Hi, I looked through the files changed on this PR but did not see `SpecialOrthogonal(N)`. Just wanted to ask if that could perhaps be added too please?

Sure, that should be doable.

> @mateuszbaran I am not yet 100% sure I am so happy with having so much code to introduce `Identity` everywhere, can we maybe do that with the group trait? something like
> `exp(::TraitList{IsGroupManifold}, M::DecoratorManifold, ::Identity, X) = exp_lie(M,X)`?
> the one ting I do not directly see here is that it in principle also has to be “the right” identity here.

I don't see how to do it your way nicely and I think it's not that much code the way I've done it. Note that the changes in Euclidean.jl are sort of unrelated, just a speed-up of some cases I've discovered while working on ManifoldDiff.jl.

**Comment by kellertuer** [comment]
Ok, if you think it is not too much to do that for every group individually, then ok.

The one thing I am not so much in favour of is

´``
exp!(::Euclidean, q, ::Identity{AdditionOperation}, X) = copyto!(q, X)
```

if one (like I tried to do on the unitary branch) tries to split (strictly) between the manifold and the group. Then this should only be for `TranslationGroup`?
The reason I would like to split that is, (a) that conceptually Euclidean is a manifold but not a Lie group (`TranslationGroup` with + is), and (b) if we have a stricter division between manifolds and Lie groups that makes it easier if we at some point do a LieGroup.jl package (maybe even together with a LieGroupBase.jl)

**Comment by mateuszbaran** [comment]
It's a lesser of two evils case. I've taken a look at the SO(n) case I'm currently working on. Everything works nicely as-is *except* `get_vector_orthogonal` that is given `Identity` it can't properly handle. but it is called from `log` on Rotations (after unwrapping group decorator). That `log` can do everything fine with `Identity` except an internal call to `get_vector_orthonormal`. So, we can either have `get_vector_orhogonal` overload for Identity on Rotations or redo the entire `log` for `SpecialOrthogonal`. The second option is conceptually nicer but requires more code duplication.

**Comment by kellertuer** [comment]
I would have thought you could dispatch on Identity for SO(n) on layer 2, before you get down to rotations?

**Comment by mateuszbaran** [comment]
Yes, for `log` I can -- that's why duplicating `log` would work. For `get_vector_orthogonal` I can't because by the time it's called the group decorator is already unwrapped.

**Comment by kellertuer** [comment]
but, (I am on something different so its not so easy to switch branch)

can't you just do two lines? Or do you also want to cover q being identity?

```
log(G::SpecialOrthogonal, ::Identity, q) = log_lie(M, q)
log!(G::SpecialOrthogonal, X, ::Identity, q) = log_lie!(M, X, q)
```

**Comment by kellertuer** [comment]
....and then we would not need the get_vector ones?

**Comment by dehann** [comment]
> @dehann What you actually do there is exp_lie :)

Ah, I did not know that, thanks!

**Comment by mateuszbaran** [comment]
> can't you just do two lines? Or do you also want to cover q being identity?

Hm, right, this works -- here and also for TranslationGroup.

> > @dehann What you actually do there is exp_lie :)
> 
> Ah, I did not know that, thanks!

Just note that they are the same for SO(n) because it has a bi-invariant metric :slightly_smiling_face: .

**Comment by mateuszbaran** [comment]
But how would you handle `log(G::ProductGroup, ::Identity, q) = ???` ? Calling `log_lie` there is not correct.

**Comment by kellertuer** [comment]
> But how would you handle `log(G::ProductGroup, ::Identity, q) = ???` ? Calling `log_lie` there is not correct.

hm, yeah the problem is that we basically have two traits to check
1) right identity tyoe
2) biinvairant metric
then call log_lie

otherwise (so with just 1) maybe materialise Identity as a default?

Also for product, I would first do the element wise logs (wee are not in the semidirect case, right?)?

**Comment by dehann** [comment]
> Just note that they are the same for SO(n) because it has a bi-invariant metric slightly_smiling_face .

Alright cool, that's good to know too thanks.

Just posting `exp_lie` I tried which might influence this PR (or next PR):
```julia
julia> exp_lie(SpecialOrthogonal(3), [0;0;0.1])
ERROR: MethodError: no method matching iterate(::LinearAlgebra.UniformScaling{Bool})
Closest candidates are:
  iterate(::Union{LinRange, StepRangeLen}) at /usr/local/share/julia-1.7.3/share/julia/base/range.jl:826
  iterate(::Union{LinRange, StepRangeLen}, ::Integer) at /usr/local/share/julia-1.7.3/share/julia/base/range.jl:826
  iterate(::T) where T<:Union{Base.KeySet{<:Any, <:Dict}, Base.ValueIterator{<:Dict}} at /usr/local/share/julia-1.7.3/share/julia/base/dict.jl:695
  ...
Stacktrace:
 [1] copyto!(dest::Vector{Float64}, src::LinearAlgebra.UniformScaling{Bool})
   @ Base ./abstractarray.jl:890
 [2] exp_lie!(#unused#::SpecialOrthogonal{3}, q::Vector{Float64}, X::Vector{Float64})
   @ Manifolds ~/.julia/packages/Manifolds/hgcQS/src/groups/general_unitary_groups.jl:101
 [3] exp_lie(#unused#::ManifoldsBase.TraitList{IsGroupManifold{MultiplicationOperation}, ManifoldsBase.TraitList{HasBiinvariantMetric, ManifoldsBase.TraitList{HasLeftInvariantMetric, ManifoldsBase.TraitList{HasRightInvariantMetric, ManifoldsBase.TraitList{IsDefaultMetric{EuclideanMetric}, ManifoldsBase.TraitList{IsMetricManifold, ManifoldsBase.TraitList{ManifoldsBase.IsExplicitDecorator, ManifoldsBase.EmptyTrait}}}}}}}, G::SpecialOrthogonal{3}, X::Vector{Float64})
   @ Manifolds ~/.julia/packages/Manifolds/hgcQS/src/groups/group.jl:871
 [4] exp_lie(M::SpecialOrthogonal{3}, X::Vector{Float64})
   @ Manifolds ~/.julia/packages/ManifoldsBase/SWdl9/src/nested_trait.jl:275
 [5] top-level scope
   @ REPL[7]:1
```

**Comment by mateuszbaran** [comment]
@kellertuer I think this is ready now.

**Comment by kellertuer** [comment]
Can you take a short look into code coverage?

**Comment by mateuszbaran** [comment]
Codecov doesn't load for me now for some reason but earlier when it did the one not covered line was a false positive (the `Test.@testset "Metric operations with Identity" begin` line)

**Comment by kellertuer** [comment]
Hm, then maybe you could check for these four in here?
https://app.codecov.io/gh/JuliaManifolds/Manifolds.jl/blobs/mbaran%2Fidentity-overloads/src/groups/group_action.jl

It would be great to fix the remaining missing lines (as long as they are not false positives) along the way of the next PRs :)

**Comment by mateuszbaran** [comment]
Your link doesn't work for me, could you copy the uncovered lines or post a screenshot?

**Comment by kellertuer** [comment]
Woah eh, Codecov, approximately as stable as a bowl of pudding, currently for me it is changing between old design, new design and errors randomly...well: 
Screenshot 2022-07-21 at 13 52 45
.

There also seem to be composite errors in SpecialEuclidean not hit but now my Codecov is again failing as well

**Comment by mateuszbaran** [comment]
Those "not covered" lines would only make sense if `allocate_result` threw an error, which would make tests fail :man_shrugging: .

**Comment by kellertuer** [comment]
so those are covered but not found? Meh.

**Comment by dehann** [comment]
Hi, random Julia comment. Test.jl does allow things like, trivial example:
```julia
@test_throws AssertionError @assert(false)
```

**Comment by kellertuer** [comment]
In what sense? It runs fine on REPL :)

**Comment by dehann** [comment]
For test coverage in code that is expected to give a specific error

**Comment by mateuszbaran** [comment]
> For test coverage in code that is expected to give a specific error
> 
> > Those "not covered" lines would only make sense if allocate_result threw an error, which would make tests fail man_shrugging .

What I meant there is that that coverage is theoretically possible (using such `@test_throws` tests) but that's not what our tests are doing there.

**Review by kellertuer — APPROVED** [review]
If you could try to not loose the line of code coverage that would be great, otherwise this looks fine.

**Comment by mateuszbaran** [comment]
I don't know how to cover that one line so I think I'll leave it like that

**Comment by kellertuer** [comment]
Ok.

**Pull request merged**
