### PR TITLE
Fix projected distribution with multiple points

### LINKED ISSUE #449: StackOverflowError: rand(uniform_distribution(sphere), 509)
As far as I've been able to understand, the right way to draw random samples from a uniform distribution on the sphere is as follows, but that errors.

```julia
sphere = Sphere(2)
haar_measure = uniform_distribution(sphere, zeros(representation_size(sphere)))
x = rand(haar_measure, 509)
```

```julia
ERROR: StackOverflowError:
Stacktrace:
 [1] rand!(rng::Random._GLOBAL_RNG, A::Vector{Any}, X::ProjectedPointDistribution{Vector{Float64}, Sphere{2, ℝ}, Distributions.IsoNormal, typeof(project!)}) (repeats 79984 times)
   @ Random /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Random/src/Random.jl:267
```

### PR DESCRIPTION
**Pull request by mateuszbaran**
Fixes #449 .

### CODE REVIEW

**Comment by mateuszbaran** [comment]
I'm also going to add
```julia
sphere = Sphere(2)
haar_measure = uniform_distribution(sphere)
```
API here but it needs https://github.com/JuliaManifolds/ManifoldsBase.jl/pull/93 to work properly.

**Review by kellertuer — APPROVED** [review]
This looks good to me and can be merged once the other PR on ManifoldsBase is done. Thanks for the quick fix.

**Comment by mateuszbaran** [comment]
Yes, I'll check coverage and add the convenience default argument after the base PR is merged.

**Comment by mateuszbaran** [comment]
I think this is ready now.

**Comment by kellertuer** [comment]
Sure, looks god.

**Pull request merged**
