### PR TITLE
Update CompatHelper to the latest recommended configuration

### PR DESCRIPTION
**Pull request by DilumAluthge**
This will fix the issue you are having with duplicated CompatHelper PRs.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
cc: @kellertuer

**Comment by kellertuer** [comment]
Thanks for the help, I will also adapt the other repositories (ManifoldsBase.jl, Manopt.jl) which are running the same config as this one.

**Comment by DilumAluthge** [comment]
If you want to update the CompatHelper setup on a whole bunch of repos at once, you might consider the [MassInstallAction.jl](https://github.com/julia-actions/MassInstallAction.jl) package. E.g.:

```julia
julia> using MassInstallAction

julia> workflow = MassInstallAction.compat_helper()

julia> MassInstallAction.install(workflow,
           "NAME_OF_GITHUB_ORGANIZATION";
           token = ENV["YOUR_GITHUB_PERSONAL_ACCESS_TOKEN"],
           cc = ["YOUR_GITHUB_USERNAME"],
       )
```

And this will install or update CompatHelper on all Julia packages in the `NAME_OF_GITHUB_ORGANIZATION` organization.

**Comment by kellertuer** [comment]
Thanks :) But it is actually just two other repositories, so I think I will do it manually.

**Comment by DilumAluthge** [comment]
Yeah for two repos, it's pretty fast to just do manually.

You can copy the CompatHelper config from either of the following two sources:
1. https://juliaregistries.github.io/CompatHelper.jl/dev/#Installation,-step-1:-Create-the-workflow-file
2. https://github.com/JuliaRegistries/CompatHelper.jl/blob/master/.github/workflows/CompatHelper.yml

The two sources are the same (number 1 is auto-generated from number 2).

**Review by kellertuer — APPROVED** [review]

**Review by mateuszbaran — APPROVED** [review]

**Pull request merged**
