### PR TITLE
Moving rand to ManifoldsBase.jl

### PR DESCRIPTION
**Pull request by mateuszbaran**
Adapt to https://github.com/JuliaManifolds/ManifoldsBase.jl/pull/141 .

### CODE REVIEW

**Comment by kellertuer** [comment]
We still have to import `rand` and `rand!` from ManifoldsBase now, I think?

**Comment by mateuszbaran** [comment]
That shouldn't be necessary, it's still a function defined in `Random`.

**Comment by kellertuer** [comment]
But it makes it more clearer where it comes from? And do we have the decorator thingy that way here?

**Review by kellertuer — APPROVED** [review]
I would prefer to import rand/rand! from ManifoldsBase to make clear it was defined there already and to be sure we have the definitions of the decorator available here... besides that this is good to go, so I‘ll approve it already.

**Comment by mateuszbaran** [comment]
OK, I'll add `import`.

**Pull request merged**
