### PR TITLE
Clear Preview on PR close

### PR DESCRIPTION
**Pull request by kellertuer**
Introduces one further GitHub Action to delete PRs previews once the PR is closed (e.g. merged).

### CODE REVIEW

**Comment by kellertuer** [comment]
What do you think about this PR? It might keep our docs branch a little bit more organised.

**Comment by mateuszbaran** [comment]
That's a good idea but I just have no idea if this action would work or not.

**Comment by kellertuer** [comment]
We can just try on the next ones. And oh, I forgot to mention the source and now I forgot where I have this one from.

**Review by mateuszbaran — APPROVED** [review]
OK, sure.

**Comment by kellertuer** [comment]
For reference here, it's a script taken from https://github.com/EcoJulia/SpatialEcology.jl/blob/master/.github/workflows/Doc_preview_cleanup.yml

**Pull request merged**
