### PR TITLE
Make format action suggest formatting changes

### PR DESCRIPTION
**Pull request by sethaxen**
This PR adapts DynamicPPL's convenient [format action](https://github.com/TuringLang/DynamicPPL.jl/blob/master/.github/workflows/Format.yml), which uses the diff generated from running the formatter to review the code and suggest formatting changes, which is more more handy than just telling the author to go run JuliaFormatter.

### CODE REVIEW

**Comment by kellertuer** [comment]
Thats a very neat feature!

**Comment by mateuszbaran** [comment]
Very cool :+1:

**Review by kellertuer — APPROVED** [review]
I think I will adapt this to Manopt.jl and ManifoldsBase.jl, too (or if you want to, feel free, to do there, too).

**Comment by sethaxen** [comment]
> I think I will adapt this to Manopt.jl and ManifoldsBase.jl, too (or if you want to, feel free, to do there, too).

Go ahead!

**Pull request merged**
