### PR TITLE
Copy and broadcasting for ProductRepr

### PR DESCRIPTION
**Pull request by mateuszbaran**
This should fix https://github.com/JuliaManifolds/Manopt.jl/issues/64 .

### CODE REVIEW

**Review by kellertuer — APPROVED** [review]

**Comment by kellertuer** [comment]
I fear the bug with Plots is not yet fixed, as far as I understand the current test result.

**Comment by mateuszbaran** [comment]
Oh, indeed. This looks like a separate bug though.

**Comment by kellertuer** [comment]
I will check for that bug soon, then.

**Comment by mateuszbaran** [comment]
Thanks!

There seems to be a problem with ambiguities but only on Windows, weird.

**Pull request merged**
