### PR TITLE
Make ArrayPartition default instead of ProductRepr

### PR DESCRIPTION
**Pull request by mateuszbaran**
Resolves one of the issues raised in #609 .

This should be only slightly breaking so I don't think an actual breaking release is necessary.

### CODE REVIEW

**Comment by kellertuer** [comment]
How breaking this is is maybe hard to estimate?
But we could introduce a default function (yet again) for this as well?

And we could also deprecate ProductRepr?

**Comment by kellertuer** [comment]
You changed quite some code for the switch, so a default data type might be helpful in case we want to switch again?

I think in favour of ArrayPartition we should deprecate ProductRepr (and remove it in 0.9), since I do not see much gain in inventing our own data type if probably better tested and maybe more efficient others do exist.

**Comment by mateuszbaran** [comment]
Most code changes is either adapting tests or adding some missing functionality to `ArrayPartition`. Actually changing the default is something like replacing `ProductRepr` with `ArrayPartition` in a few places.

I guess the only way to switch defaults would be encoding it in the manifold?

`ArrayPartition` is generally a better choice. I don't quite like the way it's printed and the linear indexing seems like a hacky and dangerous feature but it's more compatible thanks to it.

**Comment by kellertuer** [comment]
I just feel it is maybe a bit beyond what Manifolds.jl should provide, if it exists - unless there is a really good reason for ProductRepr.

The printing could be a PR to the original package then?
About the internals, you are more experienced than me.

**Comment by mateuszbaran** [comment]
@kellertuer I think this is ready :slightly_smiling_face:

**Review by kellertuer — APPROVED** [review]

**Comment by mateuszbaran** [comment]
I remember reworking Circle some time ago to make it accept one-element vectors as points and tangent vectors but the current implementation is a bit conflicted about it.

**Comment by kellertuer** [comment]
I hope we did not loose any of these in merges? I had in mind Circle works for both, yes.

**Comment by mateuszbaran** [comment]
It was a bit incorrect but I haven't checked git blame to see why.

**Pull request merged**
