### PR TITLE
Bump Julia compat to 1.10

### PR DESCRIPTION
**Pull request by gdalle**
- Bump Julia compat in `Project.toml` from 1.6 to 1.10
- Bump Manifolds version to v0.10.8
- Update CI to run on `lts`, `1` (stable) and `pre` (pre-release)
- Remove Requires and its extension shenanigans

### CODE REVIEW

**Comment by gdalle** [comment]
Do you mean #771? If so, that PR is not ready yet, you first need to tag the breaking release v0.4.0 of ManifoldDiff

**Comment by mateuszbaran** [comment]
Ah, sorry, I meant https://github.com/JuliaManifolds/Manifolds.jl/pull/772

**Comment by mateuszbaran** [comment]
And #770, because it's also ready and could be a part of single 0.10.8 release. #771 will be left for later.

**Comment by gdalle** [comment]
this is #772 :rofl:

**Comment by mateuszbaran** [comment]
I was a bit confused with the discussions split among multiple PRs :smile:

**Pull request merged**
