### PR TITLE
Injectivity radius of Sasaki metric and flatness definitions

### PR DESCRIPTION
**Pull request by mateuszbaran**
WIP. Requires https://github.com/JuliaManifolds/ManifoldsBase.jl/pull/143 and tests.

### CODE REVIEW

**Comment by mateuszbaran** [comment]
@kellertuer is it OK to merge this?

**Comment by kellertuer** [comment]
Yes, I was just thinking, we could also make Flatness a Trait (and later on Hadamard-ness).

**Comment by mateuszbaran** [comment]
Yes, we could have such traits, but that can be added separately.

**Comment by kellertuer** [comment]
Ok, sure. Then this is fine to merge.

**Pull request merged**
