### PR TITLE
Fix some typos in working-in-charts example.

### PR DESCRIPTION
**Pull request by vtjeng**

### CODE REVIEW

**Comment by kellertuer** [comment]
Thanks! The CI error is surely not your fault, that seems to be some package we use that did a breaking change without marking it correctly (or us using functions they consider internal).

**Comment by mateuszbaran** [comment]
Thanks for fixes!

The cause of failure is once again BoundaryValueDiffEq.jl, again.

**Comment by mateuszbaran** [comment]
Reported here: https://github.com/SciML/BoundaryValueDiffEq.jl/issues/171

**Comment by mateuszbaran** [comment]
CI will be fixed in #711 by upper-bounding dependencies.

**Pull request merged**
