### PR TITLE
Move more packages to weak dependencies

### PR DESCRIPTION
**Pull request by kellertuer**
As discussed in #656, this is an idea to move two further packages to weak dependencies.

I am not saying we should necessarily do that, but it is something to discuss, and I for now just spent about an hour to reorganise the code. I am not yet sure the advantages outweigh the disadvantages here

This would be a breaking change

* `ArrayPartition` will no longer be exported in Manifolds.jl
* we currently loose some default implementations on product manifolds and groups (for RecursiveArrays) and a few random functions (for staticArrays) which could also be provided again as default without the package dependency for sure.

Before checking and adopting the tests I would like to discuss whether we actually want to do this, with the disadvantages above the question is, does the reduced loading time make this worth the change?

### CODE REVIEW

**Comment by kellertuer** [comment]
Yes, now that I noticed that Oliviers PR is breaking, we could combine that with this PR and check a bit what else to break since we are at it ;)

Thanks for looking into it.

**Comment by kellertuer** [comment]
We could for example also do #701 then. That should even be a quite short PR.

**Comment by mateuszbaran** [comment]
Yes, #701 could also be done, or any other quick and breaking thing we intended to do.

**Comment by mateuszbaran** [comment]
#732 is now merged and supersedes this PR so we can close this.

**Pull request closed without merging**
