### PR TITLE
up compat BoundaryValDiffEq

### PR DESCRIPTION
**Pull request by dehann**
Hi, I found the following compat issue.  Will let PR CI tests run and see if there are any issues.

### CODE REVIEW

**Comment by dehann** [comment]
Not sure why CompatHelper did not catch this.  I looked around for related issues or PR but didn't immediately see one.

**Comment by kellertuer** [comment]
Interesting; it might be that CompatHelper does not check weak dependencies? At least the CI runs do not look like it would consider those; maybe we should check that those are included as well then.

**Comment by kellertuer** [comment]
Yes, my impression was correct, see https://github.com/JuliaRegistries/CompatHelper.jl/issues/452

**Comment by mateuszbaran** [comment]
Thanks! Before merging it would be good to check if BoundaryValueDiffEq v5 is actually used on CI.

**Comment by mateuszbaran** [comment]
Hm, there seems to be a *huge* problem with BoundaryValueDiffEq v5

**Comment by mateuszbaran** [comment]
I will close this in favor of #672 .

**Pull request closed without merging**
