### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by spaette**
Closes https://github.com/JuliaManifolds/Manifolds.jl/issues/727

### CODE REVIEW

**Review by kellertuer — APPROVED** [review]
Thanks for spotting so many typos and fixing them. 🏅

**Comment by mateuszbaran** [comment]
Thanks! I will check the CI failure, it looks unrelated to changes in this PR.

**Review by mateuszbaran — APPROVED** [review]

**Comment by kellertuer** [comment]
The CI failure is just the changelog, we can change/add a note on fixed typos in there on another PR.

**Comment by mateuszbaran** [comment]
No, there is something wrong with our FiniteDifferences.jl extension.

**Comment by mateuszbaran** [comment]
I tried fixing it in #729. Making a copy is not ideal but `FiniteDifferences.jl` doesn't like `SVector`.

**Comment by spaette** [comment]
> a note on fixed typos

please draft a note and post it here

**Comment by kellertuer** [comment]
Sure.
Start a new subheading for a new version (maybe as unreleased or with todays date) and therein have a `### Changed` subsubheading.

There you could just add a line that several typographical errors were fixed. We will add a few points in the next few PRs before we register a new version (and maybe Mateusz newest PR/fix is such a vision as well).

So maybe

```
* files several typographical errors throughout the documentation
```

?
You can also add how you encountered them, but along would be my phrasing.

**Comment by spaette** [comment]
my draft change to NEWS.md

```diff
  ## [0.9.19] – unreleased
  
  ### Changed
  
- * fixed a few typos in the doc string of the SPD fixed determinant description.
  * Updated `Project.toml` compatibility entries.
  
+ ### Fixed
+ 
+ * a few typos in the doc string of the SPD fixed determinant description
+ * several other typographical errors throughout the documentation
+ 
  ## [0.9.18] – 2024-05-07
```

**Comment by kellertuer** [comment]
Looks good. You could also just commit that here and I would comment on the code (probably even with a proposed change).

**Comment by spaette** [comment]
@kellertuer

MetricManifold.jl
another typo fixed

NEWS.md
edited as per agreement

performed soft reset

**Comment by spaette** [comment]
_cf_: failed **CI / Julia ~1.10.0-0 - test_manifolds - ubuntu-latest (pull_request)**

owing to this pull's edit of NEWS.md

it might be preferable to schedule a NEWS.md entry for whatever fix is decided upon for the cited failed test

until after this pull is merged

**Comment by kellertuer** [comment]
No worries, this is unrelated to your changes, it seems DifferentialEquations changed something they thought is nonbreaking but it actually was. This happens every now and then – I think they are just not careful enough.

But Mateusz has started the fix already at #729. And sure both PRs together would have a joint entry fpr the version then. Maybe we merge this one shortly before the other so Mateusz can take care of a joint entry :)

**Pull request merged**
